import Navbar from "../Components/NavBar/Navbar";
import SearchBar from '../Components/NavSearch/SearchBar'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GridLayout({ children }) {
  return (
    <div className="grid grid-cols-[270px_1fr] h-screen w-full max-lg:grid-cols-[90px_1fr] transition-all duration-200">
      <div className="shadow-lg">
        <Navbar />
      </div>

      <div className="h-full overflow-y-auto">
        <SearchBar></SearchBar> {children}
      </div>
    </div>
  );
}
