import Sidebar from "@/Components/navigation/sidebar/Sidebar";
import TopBar from '@/Components/navigation/top-bar/TopBar'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GridLayout({ children }) {
  return (
    <div className="grid grid-cols-[270px_1fr] h-screen w-full max-lg:grid-cols-[90px_1fr] transition-all duration-200">
      <div className="shadow-lg">
        <Sidebar />
      </div>
      <div className="h-full overflow-y-auto">
        <TopBar></TopBar> 
        {children}
      </div>
    </div>
  );
}